/**
 * RpaRow — canonical shape for every RPA project record.
 *
 * Field names mirror the CSV column headers exactly so the data-stream
 * callback can stamp rows straight into the masterPool without mapping.
 *
 * The dataStream.js parser:
 *   - Casts employee_count, annual_revenue_usd, customer_count, founded_year → parseInt
 *   - Casts market_share_percent → parseFloat
 *   - Everything else remains a string
 *   - Adds internal_uid as `uid-row-${i}`
 *
 * The CSV has 18 columns. The parser's numeric casting only applies to columns
 * whose header name matches the hardcoded list. Since the CSV column names are
 * different (robots_deployed, budget_usd, etc.), those arrive as strings and
 * must be coerced at the state engine level.
 */
export interface RpaRow {
  /** Primary key — unique across the entire dataset */
  project_id: string;

  /** Parent company identifier */
  company_id: string;

  /** Human-readable project label */
  project_name: string;

  /** ISO-8601 date string (YYYY-MM-DD) */
  start_date: string;

  /** ISO-8601 date string (YYYY-MM-DD) — may be empty for in-progress projects */
  completion_date: string;

  /** Lifecycle status — the canonical values */
  project_status: 'Active' | 'Completed' | 'Planned' | 'Failed' | string;

  /** e.g. "Customer Onboarding", "Claims Processing", etc. */
  automation_type: string;

  /** Count of bots currently deployed for this project */
  robots_deployed: number;

  /** Total allocated budget in USD */
  budget_usd: number;

  /** Annualized cost savings in USD */
  annual_savings_usd: number;

  /** Return on investment as a percentage (e.g. 142.5 → 142.50%) */
  roi_percent: number;

  /** Owning department inside the company */
  department: string;

  /** SI / consulting partner that implemented the project */
  implementation_partner: string;

  /** Country name */
  country: string;

  /** Vertical industry segment */
  industry: string;

  /** Total employee hours saved per year */
  employee_hours_saved: number;

  /** "Yes" | "No" — whether the bot uses AI/ML models */
  ai_enabled: string;

  /** "Yes" | "No" — whether deployed on cloud infrastructure */
  cloud_deployment: string;

  /** Internal tracking UID generated by dataStream.js parser */
  internal_uid: string;

  /**
   * Dynamic fields added by dataStream.js mutations.
   * These may not exist on every row object depending on whether
   * the row was mutated in a stream tick.
   */
  annual_revenue_usd?: number;
  employee_count?: number;
  customer_count?: number;
  founded_year?: number;
  market_share_percent?: number;

  /** Allow arbitrary string keys from dynamic parsing */
  [key: string]: string | number | undefined;
}

/**
 * KpiAccumulator — running totals maintained by the state engine.
 * Updated incrementally on every batch so the KPI bar never needs
 * to iterate the full masterPool.
 */
export interface KpiAccumulator {
  totalRows: number;
  totalRobots: number;
  totalSavings: number;
}

/**
 * SortDirection — ascending or descending.
 */
export type SortDirection = 'asc' | 'desc';

/**
 * SortEntry — one column + direction pair inside the sort-priority array.
 */
export interface SortEntry {
  key: keyof RpaRow;
  dir: SortDirection;
}

/**
 * FilterMap — each key is a column name, value is the set of accepted values.
 * Empty set or missing key = "show all" for that column.
 */
export type FilterMap = Partial<Record<keyof RpaRow, Set<string>>>;
